<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alldata [
        <!ELEMENT alldata (data)*>
        <!ELEMENT data (meth|part|data|contracts|men|heading|budget|time|action|parameters|status|cost|extras)*>
        <!ELEMENT meth (#PCDATA)>
        <!ELEMENT part (#PCDATA)>
        <!ELEMENT contracts (amount|resource)*>
        <!ELEMENT amount (#PCDATA)>
        <!ELEMENT resource (#PCDATA)>
        <!ELEMENT men (#PCDATA)>
        <!ELEMENT heading (#PCDATA)>
        <!ELEMENT budget (#PCDATA)>
        <!ELEMENT time (#PCDATA)>
        <!ELEMENT action (#PCDATA)>
        <!ELEMENT parameters (direction)*>
        <!ELEMENT direction (#PCDATA)>
        <!ELEMENT status (#PCDATA)>
        <!ELEMENT cost (#PCDATA)>
        <!ELEMENT extras (found|range)*>
        <!ELEMENT found (#PCDATA)>
        <!ELEMENT range (#PCDATA)>
        ]>
<alldata>
         <data>
         <meth>initialize</meth>
         <part>Engine</part>
         <data>
             <contracts>
                 <amount>1000</amount>
                 <resource>PLANK</resource>
             </contracts>
             <contracts>
                 <amount>800</amount>
                 <resource>QUARTZ</resource>
             </contracts>
             <contracts>
                 <amount>3000</amount>
                 <resource>WOOD</resource>
             </contracts>
             <contracts>
                 <amount>80</amount>
                 <resource>FLOWER</resource>
             </contracts>
             
             <men>4</men>
             <heading>E</heading>
             <budget>15000</budget>
         </data>
         <time>1452455629497</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>E</direction>
             </parameters>
         </data>
         <time>1452455629506</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>52</range>
             </extras>
         </data>
         <time>1452455629506</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>N</direction>
             </parameters>
         </data>
         <time>1452455629507</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>0</range>
             </extras>
         </data>
         <time>1452455629507</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629508</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>8</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>52</range>
             </extras>
         </data>
         <time>1452455629508</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629509</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>2</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629509</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>E</direction>
             </parameters>
         </data>
         <time>1452455629509</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>51</range>
             </extras>
         </data>
         <time>1452455629510</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>N</direction>
             </parameters>
         </data>
         <time>1452455629510</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>0</range>
             </extras>
         </data>
         <time>1452455629510</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629510</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>52</range>
             </extras>
         </data>
         <time>1452455629510</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629511</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629511</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>E</direction>
             </parameters>
         </data>
         <time>1452455629511</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>7</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>50</range>
             </extras>
         </data>
         <time>1452455629511</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>N</direction>
             </parameters>
         </data>
         <time>1452455629511</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>0</range>
             </extras>
         </data>
         <time>1452455629511</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629511</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>52</range>
             </extras>
         </data>
         <time>1452455629512</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629512</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629512</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>E</direction>
             </parameters>
         </data>
         <time>1452455629512</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>49</range>
             </extras>
         </data>
         <time>1452455629512</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>N</direction>
             </parameters>
         </data>
         <time>1452455629513</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>0</range>
             </extras>
         </data>
         <time>1452455629513</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629513</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>52</range>
             </extras>
         </data>
         <time>1452455629513</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629513</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629513</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>E</direction>
             </parameters>
         </data>
         <time>1452455629513</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>48</range>
             </extras>
         </data>
         <time>1452455629514</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>N</direction>
             </parameters>
         </data>
         <time>1452455629514</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>0</range>
             </extras>
         </data>
         <time>1452455629514</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629514</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>52</range>
             </extras>
         </data>
         <time>1452455629515</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629515</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629515</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>E</direction>
             </parameters>
         </data>
         <time>1452455629515</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>47</range>
             </extras>
         </data>
         <time>1452455629515</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>N</direction>
             </parameters>
         </data>
         <time>1452455629515</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>0</range>
             </extras>
         </data>
         <time>1452455629515</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629515</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>GROUND</found>
                 <range>28</range>
             </extras>
         </data>
         <time>1452455629516</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>heading</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629517</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629517</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>scan</action>
         </data>
         <time>1452455629517</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
                 <biomes>OCEAN</biomes>
                 
                 
             </extras>
         </data>
         <time>1452455629517</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629518</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
                 <found>GROUND</found>
                 <range>22</range>
             </extras>
         </data>
         <time>1452455629518</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629518</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629518</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629518</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
                 <found>GROUND</found>
                 <range>21</range>
             </extras>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>GROUND</found>
                 <range>20</range>
             </extras>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
                 <found>GROUND</found>
                 <range>19</range>
             </extras>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
                 <found>GROUND</found>
                 <range>18</range>
             </extras>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>2</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>GROUND</found>
                 <range>17</range>
             </extras>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629519</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>GROUND</found>
                 <range>16</range>
             </extras>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
                 <found>GROUND</found>
                 <range>15</range>
             </extras>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
                 <found>GROUND</found>
                 <range>14</range>
             </extras>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
                 <found>GROUND</found>
                 <range>13</range>
             </extras>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
                 <found>GROUND</found>
                 <range>12</range>
             </extras>
         </data>
         <time>1452455629520</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629521</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629521</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629521</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
                 <found>GROUND</found>
                 <range>11</range>
             </extras>
         </data>
         <time>1452455629521</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455629521</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
             </extras>
         </data>
         <time>1452455629521</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455629521</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>GROUND</found>