<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="style.css" type="text/css"?>
<?xml-stylesheet href="../../style.css" type="text/css"?>
<!DOCTYPE alldata [
        <!ELEMENT alldata (data)*>
        <!ELEMENT data (meth|part|data|contracts|men|heading|budget|time|action|parameters|status|cost|extras)*>
        <!ELEMENT meth (#PCDATA)>
        <!ELEMENT part (#PCDATA)>
        <!ELEMENT contracts (amount|resource)*>
        <!ELEMENT amount (#PCDATA)>
        <!ELEMENT resource (#PCDATA)>
        <!ELEMENT men (#PCDATA)>
        <!ELEMENT heading (#PCDATA)>
        <!ELEMENT budget (#PCDATA)>
        <!ELEMENT time (#PCDATA)>
        <!ELEMENT action (#PCDATA)>
        <!ELEMENT parameters (direction)*>
        <!ELEMENT direction (#PCDATA)>
        <!ELEMENT status (#PCDATA)>
        <!ELEMENT cost (#PCDATA)>
        <!ELEMENT extras (found|range)*>
        <!ELEMENT found (#PCDATA)>
        <!ELEMENT range (#PCDATA)>
        ]>
<alldata>
         <data>
         <meth>initialize</meth>
         <part>Engine</part>
         <data>
             <contracts>
                 <amount>1000</amount>
                 <resource>PLANK</resource>
             </contracts>
             <contracts>
                 <amount>800</amount>
                 <resource>QUARTZ</resource>
             </contracts>
             <contracts>
                 <amount>3000</amount>
                 <resource>WOOD</resource>
             </contracts>
             <contracts>
                 <amount>80</amount>
                 <resource>FLOWER</resource>
             </contracts>
             
             <men>4</men>
             <heading>E</heading>
             <budget>15000</budget>
         </data>
         <time>1452455594865</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>E</direction>
             </parameters>
         </data>
         <time>1452455594891</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>52</range>
             </extras>
         </data>
         <time>1452455594891</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>N</direction>
             </parameters>
         </data>
         <time>1452455594896</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>0</range>
             </extras>
         </data>
         <time>1452455594896</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455594896</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>52</range>
             </extras>
         </data>
         <time>1452455594897</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>heading</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455594899</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594899</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>heading</action>
             <parameters>
                 <direction>E</direction>
             </parameters>
         </data>
         <time>1452455594899</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594899</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>heading</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455594899</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594899</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>heading</action>
             <parameters>
                 <direction>E</direction>
             </parameters>
         </data>
         <time>1452455594900</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594900</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594900</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594900</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455594900</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
                 <found>GROUND</found>
                 <range>24</range>
             </extras>
         </data>
         <time>1452455594901</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>heading</action>
             <parameters>
                 <direction>N</direction>
             </parameters>
         </data>
         <time>1452455594902</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594902</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>heading</action>
             <parameters>
                 <direction>W</direction>
             </parameters>
         </data>
         <time>1452455594902</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594902</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>heading</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455594902</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594902</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594903</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>2</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594903</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594903</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>2</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594903</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594903</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594903</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594904</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594904</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594904</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594904</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594904</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594904</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594904</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594904</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594904</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594904</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594905</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594905</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594905</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594905</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594905</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594905</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594905</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594905</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594906</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594906</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594906</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594906</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594906</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594906</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594906</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594906</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594907</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594907</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594907</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594907</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594907</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594907</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594907</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594907</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594908</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>2</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594908</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594908</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594908</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594908</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594908</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594908</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594908</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594908</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594908</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594912</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594912</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>scan</action>
         </data>
         <time>1452455594913</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>7</cost>
             <extras>
                 <biomes>OCEAN</biomes>
                 
                 
             </extras>
         </data>
         <time>1452455594913</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455594917</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>23</range>
             </extras>
         </data>
         <time>1452455594917</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>heading</action>
             <parameters>
                 <direction>E</direction>
             </parameters>
         </data>
         <time>1452455594918</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>7</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594918</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>heading</action>
             <parameters>
                 <direction>N</direction>
             </parameters>
         </data>
         <time>1452455594918</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594918</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>scan</action>
         </data>
         <time>1452455594918</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
                 <biomes>BEACH</biomes>
                 
                 
             </extras>
         </data>
         <time>1452455594918</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594919</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594919</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>scan</action>
         </data>
         <time>1452455594919</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <biomes>BEACH</biomes>
                 
                 
             </extras>
         </data>
         <time>1452455594919</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594919</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594919</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594919</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594919</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>scan</action>
         </data>
         <time>1452455594920</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <biomes>SHRUBLAND</biomes>
                 
                 
             </extras>
         </data>
         <time>1452455594920</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594920</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594920</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>scan</action>
         </data>
         <time>1452455594920</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
                 <biomes>BEACH</biomes>
                 <biomes>SHRUBLAND</biomes>
                 
                 
             </extras>
         </data>
         <time>1452455594920</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594921</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594921</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455594921</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594921</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>scan</action>
         </data>
         <time>1452455594921</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
                 <biomes>OCEAN</biomes>
                 
                 
             </extras>
         </data>
         <time>1452455594921</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>N</direction>
             </parameters>
         </data>
         <time>1452455594921</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>23</range>
             </extras>
         </data>
         <time>1452455594922</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>heading</action>
             <parameters>
                 <direction>E</direction>
             </parameters>
         </data>
         <time>1452455594922</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455594922</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>heading</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455594922</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>7</cost>
             <extras>