<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="style.css" type="text/css"?>
<?xml-stylesheet href="../../style.css" type="text/css"?>
<!DOCTYPE alldata [
        <!ELEMENT alldata (data)*>
        <!ELEMENT data (meth|part|data|contracts|men|heading|budget|time|action|parameters|status|cost|extras)*>
        <!ELEMENT meth (#PCDATA)>
        <!ELEMENT part (#PCDATA)>
        <!ELEMENT contracts (amount|resource)*>
        <!ELEMENT amount (#PCDATA)>
        <!ELEMENT resource (#PCDATA)>
        <!ELEMENT men (#PCDATA)>
        <!ELEMENT heading (#PCDATA)>
        <!ELEMENT budget (#PCDATA)>
        <!ELEMENT time (#PCDATA)>
        <!ELEMENT action (#PCDATA)>
        <!ELEMENT parameters (direction)*>
        <!ELEMENT direction (#PCDATA)>
        <!ELEMENT status (#PCDATA)>
        <!ELEMENT cost (#PCDATA)>
        <!ELEMENT extras (found|range)*>
        <!ELEMENT found (#PCDATA)>
        <!ELEMENT range (#PCDATA)>
        ]>
<alldata>
         <data>
         <meth>initialize</meth>
         <part>Engine</part>
         <data>
             <contracts>
                 <amount>1000</amount>
                 <resource>PLANK</resource>
             </contracts>
             <contracts>
                 <amount>800</amount>
                 <resource>QUARTZ</resource>
             </contracts>
             <contracts>
                 <amount>3000</amount>
                 <resource>WOOD</resource>
             </contracts>
             <contracts>
                 <amount>80</amount>
                 <resource>FLOWER</resource>
             </contracts>
             
             <men>4</men>
             <heading>E</heading>
             <budget>15000</budget>
         </data>
         <time>1452455576548</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>N</direction>
             </parameters>
         </data>
         <time>1452455576561</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>0</range>
             </extras>
         </data>
         <time>1452455576561</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576561</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>52</range>
             </extras>
         </data>
         <time>1452455576562</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>E</direction>
             </parameters>
         </data>
         <time>1452455576562</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>52</range>
             </extras>
         </data>
         <time>1452455576563</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576563</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576563</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576563</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>52</range>
             </extras>
         </data>
         <time>1452455576564</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576564</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576564</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576564</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>7</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>52</range>
             </extras>
         </data>
         <time>1452455576565</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576565</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576565</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576565</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>52</range>
             </extras>
         </data>
         <time>1452455576566</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576566</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576566</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576567</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>OUT_OF_RANGE</found>
                 <range>52</range>
             </extras>
         </data>
         <time>1452455576568</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576569</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>2</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576570</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576570</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>7</cost>
             <extras>
                 <found>GROUND</found>
                 <range>28</range>
             </extras>
         </data>
         <time>1452455576571</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576571</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576571</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576571</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
                 <found>GROUND</found>
                 <range>23</range>
             </extras>
         </data>
         <time>1452455576572</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576572</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576572</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576572</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>GROUND</found>
                 <range>17</range>
             </extras>
         </data>
         <time>1452455576572</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576572</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576572</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576573</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>GROUND</found>
                 <range>14</range>
             </extras>
         </data>
         <time>1452455576573</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576573</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576573</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576573</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>GROUND</found>
                 <range>13</range>
             </extras>
         </data>
         <time>1452455576573</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576574</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576574</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576574</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
                 <found>GROUND</found>
                 <range>12</range>
             </extras>
         </data>
         <time>1452455576574</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576574</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576574</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576580</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>GROUND</found>
                 <range>10</range>
             </extras>
         </data>
         <time>1452455576580</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576580</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576580</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576580</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>8</cost>
             <extras>
                 <found>GROUND</found>
                 <range>9</range>
             </extras>
         </data>
         <time>1452455576580</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576581</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576581</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576581</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
                 <found>GROUND</found>
                 <range>9</range>
             </extras>
         </data>
         <time>1452455576581</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576581</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576581</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576581</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>7</cost>
             <extras>
                 <found>GROUND</found>
                 <range>8</range>
             </extras>
         </data>
         <time>1452455576581</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576581</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>2</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576581</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576582</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
                 <found>GROUND</found>
                 <range>8</range>
             </extras>
         </data>
         <time>1452455576582</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576582</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576582</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576582</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>GROUND</found>
                 <range>8</range>
             </extras>
         </data>
         <time>1452455576582</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576582</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576582</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576582</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>GROUND</found>
                 <range>7</range>
             </extras>
         </data>
         <time>1452455576583</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576583</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>2</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576583</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576583</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
                 <found>GROUND</found>
                 <range>6</range>
             </extras>
         </data>
         <time>1452455576583</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576590</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576590</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576590</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>GROUND</found>
                 <range>5</range>
             </extras>
         </data>
         <time>1452455576590</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576590</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576590</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576591</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>7</cost>
             <extras>
                 <found>GROUND</found>
                 <range>5</range>
             </extras>
         </data>
         <time>1452455576591</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576591</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>2</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576591</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576591</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
                 <found>GROUND</found>
                 <range>5</range>
             </extras>
         </data>
         <time>1452455576591</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576591</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>4</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576591</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576591</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>8</cost>
             <extras>
                 <found>GROUND</found>
                 <range>5</range>
             </extras>
         </data>
         <time>1452455576592</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576592</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>3</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576592</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576592</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
                 <found>GROUND</found>
                 <range>5</range>
             </extras>
         </data>
         <time>1452455576592</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576592</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>6</cost>
             <extras>
             </extras>
         </data>
         <time>1452455576592</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>echo</action>
             <parameters>
                 <direction>S</direction>
             </parameters>
         </data>
         <time>1452455576592</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Engine</part>
         <data>
             <status>OK</status>
             <cost>5</cost>
             <extras>
                 <found>GROUND</found>
                 <range>5</range>
             </extras>
         </data>
         <time>1452455576592</time>
     </data>
     <data>
         <meth>takeDecision</meth>
         <part>Explorer</part>
         <data>
             <action>fly</action>
         </data>
         <time>1452455576592</time>
     </data>
     <data>
         <meth>takeDecision</meth>